name: เพิ่ม issue ใหม่เข้าบอร์ดอัตโนมัติ

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: เพิ่ม issue เข้าบอร์ด
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/users/itdev3-bot/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: testing, enhancement, bug, documentation
